/* Autogenerated by png2wx.pl on Wed Jun  6 14:08:05 2012 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img__;

#endif /* ICONS_H */
