/* Autogenerated by png2wx.pl on Wed Jun  6 14:08:05 2012 */
#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif
#include <wx/mstream.h>
#include "icons.h"

wxBitmap *_img__;

void initialize_images(void)
{
	{
		wxMemoryInputStream sm("", );
		_img__ = new wxBitmap(wxImage(sm));
	}
	return;
}
