/* Autogenerated by png2wx.pl on Sat Feb 23 14:55:26 2013 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_celestial_navigation;

#endif /* ICONS_H */
