/* Autogenerated by png2wx.pl on Sat Feb 23 14:55:26 2013 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

#include <wx/filename.h>
#include <wx/mstream.h>					

extern void initialize_images(void);

extern wxBitmap *_img_celestial_navigation;

#ifdef PLUGIN_USE_SVG
extern wxString _svg_celestial_navigation;
extern wxString _svg_celestial_navigation_rollover;
extern wxString _svg_celestial_navigation_toggled;										  
#endif

#endif /* ICONS_H */
